figure;
plot(380:10:730, p28_1.real, 'or',...
380:10:730, p28_1.imaged, 'og',...
380:10:730, p28_1.matching, 'ob',...
cie.lambda, p28_1.interp_real, '.k',...
cie.lambda, p28_1.interp_imaged, '.k',...
cie.lambda, p28_1.interp_matching, '.k');

title('patch 28.1 measured and interpolated spectra')
xlabel('wavelength(nm)');
ylabel('reflectance factor')

legend('real measured',...
    'imaged measured',...
    'matching measured',...
    'real interpolated',...
    'imaged interpolated',...
    'matching interpolated');

ylim([0 1])
    
figure;
plot(380:10:730, p28_2.real, 'or',...
380:10:730, p28_2.imaged, 'og',...
380:10:730, p28_2.matching, 'ob',...
cie.lambda, p28_2.interp_real, '.k',...
cie.lambda, p28_2.interp_imaged, '.k',...
cie.lambda, p28_2.interp_matching, '.k');

title('patch 28.2 measured and interpolated spectra')
xlabel('wavelength(nm)');
ylabel('reflectance factor')

legend('real measured',...
    'imaged measured',...
    'matching measured',...
    'real interpolated',...
    'imaged interpolated',...
    'matching interpolated');

ylim([0 1])