figure;
plot(cie.lambda, cie.cmf2deg(:,1), 'r',...
cie.lambda, cie.cmf2deg(:,2), 'g',...
cie.lambda, cie.cmf2deg(:,3), 'b',...
cie.lambda, cie.cmf10deg(:,1), '--r',...
cie.lambda, cie.cmf10deg(:,2), '--g',...
cie.lambda, cie.cmf10deg(:,3), '--b');

title('CIE standard observer CMFs')
xlabel('wavelength(nm)');
ylabel('tristimulus values')

legend('x_{bar}2 deg.',...
    'y_{bar}2 deg.',...
    'z_{bar}2 deg.',...
    'x_{bar}10 deg.',...
    'y_{bar}10 deg.',...
    'z_{bar}10 deg.');
    
figure;
plot(cie.lambda, cie.illA/100, '--k',...
    cie.lambda, cie.illD50/100, '--r',...
    cie.lambda, cie.illD65/100, '--b',...
    cie.lambda, blackbody(2856,380:5:780), 'k',...
    cie.lambda, blackbody(5003,380:5:780), 'r',...
    cie.lambda, blackbody(6504,380:5:780), 'b');

ylim([0 2.5]);

title('blackbody and standard illuminant spectra');
xlabel('wavelength(nm)');
ylabel('relative power');

legend('blackbody (2856K)',...
    'blackbody (5003K)',...
    'blackbody (6504K)',...
    'illuminant A',...
    'illuminant D50',...
    'illuminant D65',...
    'Location','northwest');
    